'use client'

import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'pt' | 'en' | 'es' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Dicionário de traduções
const translations = {
  pt: {
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.quick_access': 'Acesso Rápido',
    'dashboard.manage_sessions': 'Gerenciar sessões',
    'dashboard.manage_services': 'CRUD de serviços',
    'dashboard.configure_availability': 'Configurar horários',
    'dashboard.view_revenue': 'Ver ganhos e repasses',
    'dashboard.find_professionals': 'Encontrar profissionais',
    'dashboard.settings': 'Configurações',
    'dashboard.privacy_title': 'Privacidade e Dados',
    'dashboard.privacy_desc': 'Gerencie seus dados conforme a LGPD (exportar, deletar, consentimentos)',
    // Roles
    'home.footer_contact': 'Contato',
    // Explore Therapists
    'explore.therapists.title': 'Trilhas de Bem-estar',
    'explore.therapists.subtitle': 'Conecte com terapeutas verificados e inicie sua jornada de autocuidado. Escolha entre centenas de profissionais especializados em diversos tipos de terapia.',
    'explore.therapists.featured_trails': 'Trilhas de bem-estar em destaque',
    'explore.therapists.view_all_trails': 'Ver todas',
    'explore.therapists.sort_label': 'Ordenar:',
    'explore.therapists.sort_rating': 'Melhor avaliados',
    'explore.therapists.sort_price': 'Menor preço',
    'explore.therapists.sort_recent': 'Mais recentes',
    'explore.therapists.sort_distance': 'Distância',
    'explore.therapists.results_for': 'Resultados para',
    'explore.therapists.verified': 'Terapeutas Verificados',
    'explore.therapists.found': 'profissionais encontrados',
    'explore.therapists.in': 'em',
    'explore.therapists.within': 'em um raio de',
    'explore.therapists.km': 'km',
    'explore.therapists.prev': '← Anterior',
    'explore.therapists.next': 'Próxima →',
    'explore.therapists.page_of': 'Página {page} de {total}',
    'explore.therapists.no_results_title': 'Nenhum terapeuta encontrado',
    'explore.therapists.no_results_desc': 'Tente ajustar seus filtros ou volte em breve',
    'explore.therapists.view_all': 'Ver Todos',
    'explore.therapists.online': 'Online',
    'explore.therapists.distance': '{value} km de você',
    'explore.therapists.location_unknown': 'Localização não informada',
    'explore.therapists.verified_badge': 'Verificado',
    'explore.therapists.from_price': 'A partir de',
    'explore.therapists.view_profile': 'Ver Perfil',
    'explore.therapists.services': 'Serviços:',
    'explore.therapists.more_services': '+{count} mais',
    'explore.therapists.filter_specialty': 'Especialidade:',
    'explore.therapists.all': 'Todas',
    'explore.therapists.max_price': 'Preço máximo:',
    'explore.therapists.any_price': 'Qualquer valor',
    'explore.therapists.price_100': 'Até R$ 100',
    'explore.therapists.price_150': 'Até R$ 150',
    'explore.therapists.price_200': 'Até R$ 200',
    'explore.therapists.price_300': 'Até R$ 300',
    'explore.therapists.min_rating': 'Avaliação mínima:',
    'explore.therapists.rating_all': 'Todas',
    'explore.therapists.rating_3': '3+ ⭐',
    'explore.therapists.rating_4': '4+ ⭐',
    'explore.therapists.rating_45': '4.5+ ⭐',
    'explore.therapists.city': 'Cidade:',
    'explore.therapists.city_placeholder': 'Ex: São Paulo',
    'explore.therapists.clear_filters': 'Limpar todos os filtros',
    'explore.therapists.saved': 'Terapeutas que você salvou para agendar depois',
    // Favorites
    'favorites.title': 'Meus Favoritos',
    'favorites.subtitle': 'Terapeutas que você salvou para agendar depois',
    'favorites.empty_title': 'Nenhum favorito ainda',
    'favorites.empty_desc': 'Explore terapeutas e salve seus favoritos clicando no ícone de coração',
    'favorites.explore_button': 'Explorar Terapeutas',
    'favorites.from_price': 'A partir de R$',
    'favorites.services': 'Serviços:',
    'favorites.more_services': '+{count} mais',
    'favorites.view_profile': 'Ver Perfil e Agendar',
    'role.client': 'Cliente',
    'role.space': 'Espaço Terapêutico',
    'role.admin': 'Admin',
    // Auth - Sign In
    'auth.signin.welcome': 'Bem-vindo de volta',
    'auth.signin.subtitle': 'Entre com sua conta para continuar sua jornada',
    'auth.signin.email': 'E-mail',
    'auth.signin.email_placeholder': 'seu@email.com',
    'auth.signin.password': 'Senha',
    'auth.signin.password_placeholder': '••••••••',
    'auth.signin.forgot_password': 'Esqueceu a senha?',
    'auth.signin.signin_button': 'Entrar',
    'auth.signin.signing_in': 'Entrando...',
    'auth.signin.verified': 'E-mail verificado com sucesso! Você já pode entrar.',
    'auth.signin.resend_button': 'Reenviar e-mail de verificação',
    'auth.signin.resend_success': 'E-mail reenviado! Verifique sua caixa de entrada.',
    'auth.signin.resend_error': 'Erro ao reenviar e-mail',
    'auth.signin.enter_email': 'Digite seu e-mail primeiro',
    'auth.signin.or': 'ou',
    'auth.signin.no_account': 'Não tem uma conta?',
    'auth.signin.signup_link': 'Criar conta',
    'auth.signin.secure': 'Seguro e confiável',
    'auth.signin.fast': 'Acesso instantâneo',
    'auth.signin.hero_title': 'Transforme sua jornada de bem-estar',
    'auth.signin.hero_subtitle': 'Conecte-se com os melhores terapeutas e descubra terapias que transformam vidas.',
    'auth.signin.stat_users': 'Usuários ativos',
    'auth.signin.stat_sessions': 'Sessões realizadas',
    'auth.signin.stat_therapies': 'Terapias disponíveis',
    'auth.signin.stat_rating': 'Avaliação média',
    // Navbar
    'navbar.home': 'Início',
    'navbar.bookings': 'Agendamentos',
    'navbar.services': 'Serviços',
    'navbar.availability': 'Horários',
    'navbar.revenue': 'Receitas',
    'navbar.explore': 'Explorar',
    'navbar.therapies': 'Terapias',
    'navbar.favorites': 'Favoritos',
    'navbar.dashboard': 'Dashboard',
    'navbar.approvals': 'Aprovações',
    'navbar.users': 'Usuários',
    'navbar.bookings_admin': 'Agendamentos',
    'navbar.news': 'Notícias',
    'navbar.reports': 'Relatórios',
    'navbar.reviews': 'Avaliações',
    'navbar.payments': 'Pagamentos',
    'navbar.logout': 'Sair',
    'navbar.profile': 'Meu Perfil',
    'navbar.login': 'Entrar',
    'navbar.signup': 'Cadastrar',
    'navbar.language': 'Idioma',
    'navbar.documents': 'Documentos',
    'navbar.therapists': 'Terapeutas',
    'navbar.my_bookings': 'Meus Agendamentos',
    // Dashboard Admin
    'admin.dashboard_title': 'Dashboard Administrativo',
    'admin.total_users': 'Total de Usuários',
    'admin.therapists': 'Terapeutas',
    'admin.clients': 'Clientes',
    'admin.spaces': 'Espaços',
    'admin.pending_therapists': 'Terapeutas Pendentes',
    'admin.total_bookings': 'Total de Agendamentos',
    'admin.total_revenue': 'Receita Total',
    // News
    'news.title': 'Notícias',
    'news.new_article': 'Nova Notícia',
    'news.edit_article': 'Editar Artigo',
    'news.no_articles': 'Nenhuma notícia publicada',
    'news.create_first': 'Criar primeira notícia',
    'news.title_field': 'Título',
    'news.slug_field': 'URL Amigável (Slug)',
    'news.description_field': 'Descrição (Resumo)',
    'news.content_field': 'Conteúdo',
    'news.thumbnail_field': 'URL da Imagem de Capa',
    'news.published': 'Publicado',
    'news.draft': 'Rascunho',
    'news.featured': 'Destaque',
    'news.mark_featured': 'Marcar como destaque',
    'news.save_article': 'Salvar Artigo',
    'news.saving': 'Salvando...',
    'news.delete_confirm': 'Tem certeza que deseja deletar',
    // Reports
    'reports.title': 'Relatórios & Análises',
    'reports.subtitle': 'Visão geral de desempenho e estatísticas da plataforma',
    'reports.total_users': 'Total de Usuários',
    'reports.clients': 'Clientes',
    'reports.therapists': 'Terapeutas',
    'reports.bookings': 'Agendamentos',
    'reports.revenue_30d': 'Receita (30d)',
    'reports.bookings_by_day': 'Agendamentos por Dia (últimos 30 dias)',
    'reports.users_distribution': 'Distribuição de Usuários por Tipo',
    'reports.top_therapists': 'Top 5 Terapeutas por Agendamentos',
    'reports.no_bookings': 'Nenhum agendamento registrado',
    // Reviews
    'reviews.title': 'Avaliações & Reviews',
    'reviews.subtitle': 'Moderação de avaliações dos clientes sobre terapeutas',
    'reviews.total_reviews': 'Total de Avaliações',
    'reviews.avg_rating': 'Classificação Média',
    'reviews.distribution': 'Distribuição de Votos',
    'reviews.all': 'Todos',
    'reviews.flagged': 'Reportado',
    'reviews.approved': 'Aprovado',
    'reviews.no_reviews': 'Nenhuma avaliação disponível',
    'reviews.flag': 'Marcar como Problemático',
    'reviews.approve': 'Aprovar',
    'reviews.delete': 'Deletar',
    'reviews.delete_confirm': 'Tem certeza que deseja deletar este review?',
    // Payments
    'payments.title': 'Pagamentos',
    'payments.subtitle': 'Gerenciamento de transações e reembolsos',
    'payments.total_transactions': 'Total em Transações',
    'payments.pending': 'Pendentes',
    'payments.refunded': 'Reembolsados',
    'payments.success_rate': 'Taxa de Sucesso',
    'payments.completed': 'Concluído',
    'payments.failed': 'Falhou',
    'payments.search_placeholder': 'Buscar por terapeuta, cliente ou transação...',
    'payments.all': 'Todos',
    'payments.transaction': 'Transação',
    'payments.therapist_client': 'Terapeuta / Cliente',
    'payments.amount': 'Valor',
    'payments.status': 'Status',
    'payments.date': 'Data',
    'payments.actions': 'Ações',
    'payments.refund': 'Reembolsar',
    'payments.processing': 'Processando...',
    'payments.no_transactions': 'Nenhuma transação registrada',
    'payments.refund_confirm': 'Tem certeza que deseja reembolsar',
    // Genérico
    'common.search': 'Buscar...',
    'common.filter': 'Filtrar',
    'common.delete': 'Deletar',
    'common.edit': 'Editar',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Carregando...',
    'common.error': 'Erro ao carregar dados',
    'common.by': 'Por',
    'common.client': 'Cliente',
    // Checkout e Booking
    'checkout.title': 'Confirme seu agendamento',
    'checkout.subtitle': 'Revise os detalhes antes de finalizar',
    'checkout.incomplete': 'Dados de agendamento incompletos',
    'checkout.back': 'Voltar',
    'checkout.appointment_details': 'Detalhes do Agendamento',
    'checkout.therapist': 'Terapeuta',
    'checkout.service': 'Serviço',
    'checkout.date_time': 'Data e Hora',
    'checkout.payment_method': 'Forma de Pagamento',
    'checkout.credit_card': 'Cartão de Crédito',
    'checkout.pix': 'PIX (em breve)',
    'checkout.cancellation_policy': 'Política de Cancelamento',
    'checkout.cancellation_24h': 'Cancelamentos com 24h+ de antecedência: reembolso 100%',
    'checkout.cancellation_less24h': 'Cancelamentos com até 24h: taxa de 50%',
    'checkout.summary': 'Resumo',
    'checkout.session_value': 'Valor da sessão',
    'checkout.senda_fee': 'Taxa Senda (15%)',
    'checkout.total': 'Total',
    'checkout.therapist_receives': 'O terapeuta receberá R$ {amount} após a sessão ser realizada',
    'checkout.confirm_payment': 'Confirmar Pagamento',
    'checkout.processing': 'Processando...',
    'checkout.error': 'Erro ao processar pagamento',
    'checkout.success_message': 'Pagamento realizado com sucesso!',
    // Booking Success
    'booking.success_title': 'Tudo certo!',
    'booking.success_message': 'Sua sessão foi agendada com sucesso. Enviamos um e-mail de confirmação com todos os detalhes.',
    'booking.booking_number': 'Número do agendamento',
    'booking.loading_details': 'Carregando detalhes...',
    'booking.confirmed_availability': 'Verificamos a disponibilidade',
    'booking.slot_reserved': 'Seu horário está reservado',
    'booking.email_confirmation': 'Confirmação por e-mail',
    'booking.email_reminder': 'Você receberá lembretes 24h antes',
    'booking.secure_access': 'Acesso seguro',
    'booking.manage_anytime': 'Gerencie seu agendamento a qualquer hora',
    'booking.my_bookings': 'Ir para meus agendamentos',
    'booking.book_another': 'Agendar outra sessão',
    'booking.cancellation_info': 'Pode mudar de ideia? Você pode cancelar com reembolso total até 24h antes da sessão.',
    // Therapist Booking Section
    'therapist.services': 'Serviços',
    'therapist.no_services': 'Este terapeuta não possui serviços disponíveis no momento.',
    'therapist.schedule_session': 'Agendar Sessão',
    'therapist.choose_time': 'Escolher Horário',
    'therapist.available_online': 'Disponível online',
    'therapist.select_slot': 'Escolha um horário',
    'therapist.with': 'Com {name}',
    // Therapist Page
    'therapist.title': 'Perfil do Terapeuta',
    'therapist.about': 'Sobre',
    'therapist.experience': 'Experiência',
    'therapist.education': 'Educação',
    'therapist.certifications': 'Certificações',
    'therapist.specialties': 'Especialidades',
    'therapist.rating': 'Avaliação',
    'therapist.reviews': 'Avaliações',
    'therapist.no_reviews': 'Nenhuma avaliação ainda',
    'therapist.add_to_favorites': 'Adicionar aos favoritos',
    'therapist.remove_from_favorites': 'Remover dos favoritos',
    'therapist.minutes': 'minutos',
    // Serviços do Terapeuta
    'therapist.duration': 'Duração',
    'therapist.from': 'A partir de',
    'therapist.schedule': 'Agendar',
    'therapist.created_by': 'Criado por',
    // Trails e Cursos
    'trails.title': 'Trilhas de Aprendizado',
    'trails.category': 'Categoria',
    'trails.days': 'dias',
    'trails.lessons': 'lições',
    'trails.start_trail': 'Começar Trilha',
    'trails.starting': 'Iniciando...',
    'trails.progress': 'Progresso',
    'trails.of': 'de',
    'trails.completed': '✓ Concluída',
    'trails.lessons_title': 'Aulas',
    'trails.lesson_number': 'Aula',
    'trails.content_type': 'Tipo',
    'trails.text': 'Texto',
    'trails.audio': 'Áudio',
    'trails.video': 'Vídeo',
    'trails.mark_complete': 'Marcar como Concluída',
    'trails.browser_no_audio': 'Seu navegador não suporta áudio',
    'trails.error_enrolling': 'Falha ao enrollar',
    'trails.error_general': 'Erro ao iniciar trilha',
    // Legal e Geral
    'legal.terms': 'Termos de Serviço',
    'legal.privacy': 'Política de Privacidade',
    'legal.cancellation': 'Política de Cancelamento',
    'legal.related_documents': 'Documentos Relacionados',
    'legal.lgpd_compliance': 'Conformidade LGPD',
    // Discover/Exploração
    'discover.therapists': 'Descubra Terapeutas Verificados',
    'discover.verified': 'Verificado',
    'discover.therapist_image': 'Imagem do Terapeuta',
    'discover.search_placeholder': 'Busque por local, especialidade, terapeuta...',
    'discover.search_results': 'Terapeutas',
    'discover.new_terms': 'Novos Termos de Serviço',
    // Erro de E-mail
    'email.error_booking_confirmation': 'Erro ao enviar confirmação de agendamento',
    'email.error_therapist_notification': 'Erro ao notificar terapeuta',
    'email.error_cancellation': 'Erro ao enviar cancelamento',
    'email.explore_therapists': 'Explorar Terapeutas',
    'email.dashboard_therapist': 'Dashboard do Terapeuta',
    'email.see_booking_details': 'Ver Detalhes do Agendamento',
    // Home (Landing)
    'home.logo_alt': 'Senda - Seu caminho de autocuidado',
    'home.tagline_prefix': 'Seu caminho de',
    'home.tagline_highlight': 'autocuidado',
    'home.hero_paragraph': 'Bem-estar não é um destino, é uma jornada. Conectamos você a profissionais verificados e espaços acolhedores para trilhar seu caminho de cuidado pessoal.',
    'home.cta_explore_therapists': 'Explorar Terapeutas',
    'home.cta_create_account': 'Criar Conta',
    'home.have_account': 'Já tem uma conta?',
    'home.sign_in': 'Entrar',
    'home.highlights_title': '✨ Destaques do Mês',
    'home.highlights_subtitle': 'Promoções exclusivas e novidades para sua jornada de bem-estar',
    'home.highlight1_title': 'Primeira Sessão Grátis',
    'home.highlight1_desc': 'Experimente gratuitamente sua primeira sessão com terapeutas selecionados',
    'home.highlight1_link': 'Ver terapeutas →',
    'home.highlight2_title': 'Pacotes com 20% OFF',
    'home.highlight2_desc': 'Adquira pacotes de 5 ou 10 sessões e economize em sua jornada',
    'home.highlight2_link': 'Conhecer terapias →',
    'home.highlight3_title': 'Novos Terapeutas',
    'home.highlight3_desc': 'Conheça os profissionais que acabaram de se juntar à plataforma',
    'home.highlight3_link': 'Descobrir →',
    'home.how_title': 'Como funciona?',
    'home.how_subtitle': 'Três passos simples para iniciar sua jornada de bem-estar',
    'home.feature1_title': 'Descubra',
    'home.feature1_desc': 'Explore nosso catálogo de profissionais verificados. Filtre por especialidade, avaliações e localização para encontrar quem ressoa com você.',
    'home.feature2_title': 'Agende',
    'home.feature2_desc': 'Reserve sessões com facilidade. Escolha data e horário que se encaixam na sua rotina. Pagamento seguro e confirmação instantânea.',
    'home.feature3_title': 'Evolua',
    'home.feature3_desc': 'Viva sua sessão e acompanhe seu progresso. Avalie sua experiência e continue trilhando seu caminho de autocuidado.',
    'home.trust_title_prefix': 'Profissionais',
    'home.trust_title_highlight': 'verificados',
    'home.trust_paragraph': 'Todos os terapeutas passam por um rigoroso processo de verificação. Checamos credenciais, formação acadêmica e experiência profissional.',
    'home.trust_bullet1': 'Registro profissional validado (CRP, certificações)',
    'home.trust_bullet2': 'Avaliações reais de clientes verificados',
    'home.trust_bullet3': 'Política de cancelamento humanizada',
    'home.cta_title': 'Pronto para começar sua jornada?',
    'home.cta_subtitle': 'Junte-se a centenas de pessoas que escolheram o autocuidado como prioridade.',
    'home.cta_button': 'Criar Conta Gratuita',
    'home.footer_tagline': 'Seu caminho de autocuidado começa aqui.',
    'home.footer_for_clients': 'Para Clientes',
    'home.footer_for_professionals': 'Para Profissionais',
    'home.footer_support': 'Suporte',
    'home.footer_help_center': 'Central de Ajuda',
    'home.footer_contact': 'Contato',
    // Explore Therapies
    'explore.therapies.title': 'Explorar Terapias',
    'explore.therapies.subtitle': 'Descubra as melhores práticas terapêuticas para sua jornada de bem-estar',
    'explore.therapies.search_placeholder': 'Busque por terapia, indicação, modalidade...',
    'explore.therapies.filter_by_category': 'Filtrar por Categoria',
    'explore.therapies.filter_by_indication': 'Filtrar por Indicação Terapêutica',
    'explore.therapies.indications': 'Indicações',
    'explore.therapies.contraindications': 'Contra-indicações',
    'explore.therapies.presencial': 'Presencial',
    'explore.therapies.online': 'Online',
    'explore.therapies.presencial_online': 'Presencial/Online',
    'explore.therapies.find_therapist': 'Encontrar Terapeuta',
    'explore.therapies.clear_filters': 'Limpar Filtros',
    'explore.therapies.no_results': 'Nenhuma terapia encontrada com esses filtros.',
    'explore.therapies.more_info': 'Mais info',
    'explore.therapies.less_info': 'Menos info',
  },
  en: {
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.quick_access': 'Quick Access',
    'dashboard.manage_sessions': 'Manage sessions',
    'dashboard.manage_services': 'Manage services',
    'dashboard.configure_availability': 'Configure availability',
    'dashboard.view_revenue': 'View revenue and payouts',
    'dashboard.find_professionals': 'Find professionals',
    'dashboard.settings': 'Settings',
    'dashboard.privacy_title': 'Privacy & Data',
    'dashboard.privacy_desc': 'Manage your data under GDPR-equivalent (export, delete, consents)',
    // Roles
    'role.therapist': 'Therapist',
    'role.client': 'Client',
    'role.space': 'Therapy Space',
    'role.admin': 'Admin',
    // Auth - Sign In
    'auth.signin.welcome': 'Welcome back',
    'auth.signin.subtitle': 'Sign in to your account to continue your journey',
    'auth.signin.email': 'Email',
    'auth.signin.email_placeholder': 'your@email.com',
    'auth.signin.password': 'Password',
    'auth.signin.password_placeholder': '••••••••',
    'auth.signin.forgot_password': 'Forgot password?',
    'auth.signin.signin_button': 'Sign in',
    'auth.signin.signing_in': 'Signing in...',
    'auth.signin.verified': 'Email verified successfully! You can now sign in.',
    'auth.signin.no_verification': 'Didn\'t receive verification email?',
    'auth.signin.resend_button': 'Resend verification email',
    'auth.signin.resend_success': 'Email resent! Check your inbox.',
    'auth.signin.resend_error': 'Error resending email',
    'auth.signin.enter_email': 'Enter your email first',
    'auth.signin.or': 'or',
    'auth.signin.no_account': 'Don\'t have an account?',
    'auth.signin.signup_link': 'Sign up',
    'auth.signin.secure': 'Secure & trusted',
    'auth.signin.fast': 'Instant access',
    'auth.signin.hero_title': 'Transform your wellness journey',
    'auth.signin.hero_subtitle': 'Connect with the best therapists and discover life-changing therapies.',
    'auth.signin.stat_users': 'Active users',
    'auth.signin.stat_sessions': 'Sessions completed',
    'auth.signin.stat_therapies': 'Available therapies',
    'auth.signin.stat_rating': 'Average rating',
    // Navbar
    'navbar.home': 'Home',
    'navbar.bookings': 'Bookings',
    'navbar.services': 'Services',
    'navbar.availability': 'Availability',
    'navbar.revenue': 'Revenue',
    'navbar.explore': 'Explore',
    'navbar.therapies': 'Therapies',
    'navbar.favorites': 'Favorites',
    'navbar.dashboard': 'Dashboard',
    'navbar.approvals': 'Approvals',
    'navbar.users': 'Users',
    'navbar.bookings_admin': 'Bookings',
    'navbar.news': 'News',
    'navbar.reports': 'Reports',
    'navbar.reviews': 'Reviews',
    'navbar.payments': 'Payments',
    'navbar.logout': 'Logout',
    'navbar.profile': 'My Profile',
    'navbar.login': 'Sign In',
    'navbar.signup': 'Sign Up',
    'navbar.language': 'Language',
    'navbar.documents': 'Documents',
    'navbar.therapists': 'Therapists',
    'navbar.my_bookings': 'My Bookings',
    // Dashboard Admin
    'admin.dashboard_title': 'Admin Dashboard',
    'admin.total_users': 'Total Users',
    'admin.therapists': 'Therapists',
    'admin.clients': 'Clients',
    'admin.spaces': 'Spaces',
    'admin.pending_therapists': 'Pending Therapists',
    'admin.total_bookings': 'Total Bookings',
    'admin.total_revenue': 'Total Revenue',
    // News
    'news.title': 'News',
    'news.new_article': 'New Article',
    'news.edit_article': 'Edit Article',
    'news.no_articles': 'No articles published',
    'news.create_first': 'Create first article',
    'news.title_field': 'Title',
    'news.slug_field': 'URL Slug',
    'news.description_field': 'Description (Summary)',
    'news.content_field': 'Content',
    'news.thumbnail_field': 'Cover Image URL',
    'news.published': 'Published',
    'news.draft': 'Draft',
    'news.featured': 'Featured',
    'news.mark_featured': 'Mark as featured',
    'news.save_article': 'Save Article',
    'news.saving': 'Saving...',
    'news.delete_confirm': 'Are you sure you want to delete',
    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.subtitle': 'Platform performance overview and statistics',
    'reports.total_users': 'Total Users',
    'reports.clients': 'Clients',
    'reports.therapists': 'Therapists',
    'reports.bookings': 'Bookings',
    'reports.revenue_30d': 'Revenue (30d)',
    'reports.bookings_by_day': 'Bookings by Day (last 30 days)',
    'reports.users_distribution': 'User Distribution by Type',
    'reports.top_therapists': 'Top 5 Therapists by Bookings',
    'reports.no_bookings': 'No bookings recorded',
    // Reviews
    'reviews.title': 'Reviews & Ratings',
    'reviews.subtitle': 'Moderation of client reviews about therapists',
    'reviews.total_reviews': 'Total Reviews',
    'reviews.avg_rating': 'Average Rating',
    'reviews.distribution': 'Vote Distribution',
    'reviews.all': 'All',
    'reviews.flagged': 'Flagged',
    'reviews.approved': 'Approved',
    'reviews.no_reviews': 'No reviews available',
    'reviews.flag': 'Flag as Problematic',
    'reviews.approve': 'Approve',
    'reviews.delete': 'Delete',
    'reviews.delete_confirm': 'Are you sure you want to delete this review?',
    // Payments
    'payments.title': 'Payments',
    'payments.subtitle': 'Transaction and refund management',
    'payments.total_transactions': 'Total Transactions',
    'payments.pending': 'Pending',
    'payments.refunded': 'Refunded',
    'payments.success_rate': 'Success Rate',
    'payments.completed': 'Completed',
    'payments.failed': 'Failed',
    'payments.search_placeholder': 'Search by therapist, client or transaction...',
    'payments.all': 'All',
    'payments.transaction': 'Transaction',
    'payments.therapist_client': 'Therapist / Client',
    'payments.amount': 'Amount',
    'payments.status': 'Status',
    'payments.date': 'Date',
    'payments.actions': 'Actions',
    'payments.refund': 'Refund',
    'payments.processing': 'Processing...',
    'payments.no_transactions': 'No transactions recorded',
    'payments.refund_confirm': 'Are you sure you want to refund',
    // Common
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.error': 'Error loading data',
    'common.by': 'By',
    'common.client': 'Client',
    // Checkout and Booking
    'checkout.title': 'Confirm your appointment',
    'checkout.subtitle': 'Review details before completing',
    'checkout.incomplete': 'Appointment data incomplete',
    'checkout.back': 'Back',
    'checkout.appointment_details': 'Appointment Details',
    'checkout.therapist': 'Therapist',
    'checkout.service': 'Service',
    'checkout.date_time': 'Date & Time',
    'checkout.payment_method': 'Payment Method',
    'checkout.credit_card': 'Credit Card',
    'checkout.pix': 'PIX (coming soon)',
    'checkout.cancellation_policy': 'Cancellation Policy',
    'checkout.cancellation_24h': 'Cancellations with 24h+ notice: 100% refund',
    'checkout.cancellation_less24h': 'Cancellations with up to 24h notice: 50% fee',
    'checkout.summary': 'Summary',
    'checkout.session_value': 'Session value',
    'checkout.senda_fee': 'Senda Fee (15%)',
    'checkout.total': 'Total',
    'checkout.therapist_receives': 'The therapist will receive R$ {amount} after the session is completed',
    'checkout.confirm_payment': 'Confirm Payment',
    'checkout.processing': 'Processing...',
    'checkout.error': 'Error processing payment',
    'checkout.success_message': 'Payment processed successfully!',
    // Booking Success
    'booking.success_title': 'All set!',
    'booking.success_message': 'Your session has been booked successfully. We sent a confirmation email with all the details.',
    'booking.booking_number': 'Booking number',
    'booking.loading_details': 'Loading details...',
    'booking.confirmed_availability': 'We confirmed availability',
    'booking.slot_reserved': 'Your time slot is reserved',
    'booking.email_confirmation': 'Email confirmation',
    'booking.email_reminder': 'You will receive reminders 24h before',
    'booking.secure_access': 'Secure access',
    'booking.manage_anytime': 'Manage your appointment anytime',
    'booking.my_bookings': 'Go to my bookings',
    'booking.book_another': 'Book another session',
    'booking.cancellation_info': 'Change your mind? You can cancel with full refund up to 24h before the session.',
    // Therapist Booking Section
    'therapist.services': 'Services',
    'therapist.no_services': 'This therapist does not have available services at the moment.',
    'therapist.schedule_session': 'Schedule Session',
    'therapist.choose_time': 'Choose Time Slot',
    'therapist.available_online': 'Available online',
    'therapist.select_slot': 'Select a time slot',
    'therapist.with': 'With {name}',
    // Therapist Page
    'therapist.title': 'Therapist Profile',
    'therapist.about': 'About',
    'therapist.experience': 'Experience',
    'therapist.education': 'Education',
    'therapist.certifications': 'Certifications',
    'therapist.specialties': 'Specialties',
    'therapist.rating': 'Rating',
    'therapist.reviews': 'Reviews',
    'therapist.no_reviews': 'No reviews yet',
    'therapist.add_to_favorites': 'Add to favorites',
    'therapist.remove_from_favorites': 'Remove from favorites',
    'therapist.minutes': 'minutes',
    // Therapist Services
    'therapist.duration': 'Duration',
    'therapist.from': 'From',
    'therapist.schedule': 'Schedule',
    'therapist.created_by': 'Created by',
    // Trails and Courses
    'trails.title': 'Learning Trails',
    'trails.category': 'Category',
    'trails.days': 'days',
    'trails.lessons': 'lessons',
    'trails.start_trail': 'Start Trail',
    'trails.starting': 'Starting...',
    'trails.progress': 'Progress',
    'trails.of': 'of',
    'trails.completed': '✓ Completed',
    'trails.lessons_title': 'Lessons',
    'trails.lesson_number': 'Lesson',
    'trails.content_type': 'Type',
    'trails.text': 'Text',
    'trails.audio': 'Audio',
    'trails.video': 'Video',
    'trails.mark_complete': 'Mark as Complete',
    'trails.browser_no_audio': 'Your browser does not support audio',
    'trails.error_enrolling': 'Failed to enroll',
    'trails.error_general': 'Error starting trail',
    // Legal and General
    'legal.terms': 'Terms of Service',
    'legal.privacy': 'Privacy Policy',
    'legal.cancellation': 'Cancellation Policy',
    'legal.related_documents': 'Related Documents',
    'legal.lgpd_compliance': 'GDPR Compliance',
    // Discover/Explore
    'discover.therapists': 'Discover Verified Therapists',
    'discover.verified': 'Verified',
    'discover.therapist_image': 'Therapist Image',
    'discover.search_placeholder': 'Search by location, specialty, therapist...',
    'discover.search_results': 'Therapists',
    'discover.new_terms': 'New Terms of Service',
    // Email Errors
    'email.error_booking_confirmation': 'Error sending booking confirmation',
    'email.error_therapist_notification': 'Error notifying therapist',
    'email.error_cancellation': 'Error sending cancellation',
    'email.explore_therapists': 'Explore Therapists',
    'email.dashboard_therapist': 'Therapist Dashboard',
    'email.see_booking_details': 'See Booking Details',
    // Home (Landing)
    'home.logo_alt': 'Senda - Your path to self-care',
    'home.tagline_prefix': 'Your path to',
    'home.tagline_highlight': 'self-care',
    'home.hero_paragraph': 'Wellness is not a destination, it is a journey. We connect you with verified professionals and welcoming spaces to support your self-care path.',
    'home.cta_explore_therapists': 'Explore Therapists',
    'home.cta_create_account': 'Create Account',
    'home.have_account': 'Already have an account?',
    'home.sign_in': 'Sign in',
    'home.highlights_title': '✨ Highlights of the Month',
    'home.highlights_subtitle': 'Exclusive promotions and news for your wellness journey',
    'home.highlight1_title': 'First Session Free',
    'home.highlight1_desc': 'Try your first session for free with selected therapists',
    'home.highlight1_link': 'See therapists →',
    'home.highlight2_title': 'Packages 20% OFF',
    'home.highlight2_desc': 'Get 5 or 10-session packages and save on your journey',
    'home.highlight2_link': 'Explore therapies →',
    'home.highlight3_title': 'New Therapists',
    'home.highlight3_desc': 'Meet the professionals who just joined the platform',
    'home.highlight3_link': 'Discover →',
    'home.how_title': 'How it works',
    'home.how_subtitle': 'Three simple steps to start your wellness journey',
    'home.feature1_title': 'Discover',
    'home.feature1_desc': 'Explore our catalog of verified professionals. Filter by specialty, ratings and location to find your best match.',
    'home.feature2_title': 'Book',
    'home.feature2_desc': 'Schedule sessions easily. Choose date and time that fit your routine. Secure payment and instant confirmation.',
    'home.feature3_title': 'Evolve',
    'home.feature3_desc': 'Live your session and track your progress. Rate your experience and keep going on your self-care path.',
    'home.trust_title_prefix': 'Verified',
    'home.trust_title_highlight': 'professionals',
    'home.trust_paragraph': 'All therapists go through a rigorous verification process. We check credentials, academic background and professional experience.',
    'home.trust_bullet1': 'Professional registration validated (licenses, certifications)',
    'home.trust_bullet2': 'Real reviews from verified clients',
    'home.trust_bullet3': 'Humanized cancellation policy',
    'home.cta_title': 'Ready to start your journey?',
    'home.cta_subtitle': 'Join hundreds who chose self-care as a priority.',
    'home.cta_button': 'Create Free Account',
    'home.footer_tagline': 'Your self-care path starts here.',
    'home.footer_for_clients': 'For Clients',
    'home.footer_for_professionals': 'For Professionals',
    'home.footer_support': 'Support',
    'home.footer_help_center': 'Help Center',
    'home.footer_contact': 'Contact',
    // Explore Therapists
    'explore.therapists.title': 'Wellness Trails',
    'explore.therapists.subtitle': 'Connect with verified therapists and start your self-care journey. Choose from hundreds of specialized professionals.',
    'explore.therapists.featured_trails': 'Featured wellness trails',
    'explore.therapists.view_all_trails': 'View all',
    'explore.therapists.sort_label': 'Sort:',
    'explore.therapists.sort_rating': 'Top rated',
    'explore.therapists.sort_price': 'Lowest price',
    'explore.therapists.sort_recent': 'Most recent',
    'explore.therapists.sort_distance': 'Distance',
    'explore.therapists.results_for': 'Results for',
    'explore.therapists.verified': 'Verified Therapists',
    'explore.therapists.found': 'professionals found',
    'explore.therapists.in': 'in',
    'explore.therapists.within': 'within',
    'explore.therapists.km': 'km',
    'explore.therapists.prev': '← Previous',
    'explore.therapists.next': 'Next →',
    'explore.therapists.page_of': 'Page {page} of {total}',
    'explore.therapists.no_results_title': 'No therapists found',
    'explore.therapists.no_results_desc': 'Try adjusting your filters or come back soon',
    'explore.therapists.view_all': 'View All',
    'explore.therapists.online': 'Online',
    'explore.therapists.distance': '{value} km away',
    'explore.therapists.location_unknown': 'Location not provided',
    'explore.therapists.verified_badge': 'Verified',
    'explore.therapists.from_price': 'From',
    'explore.therapists.view_profile': 'View Profile',
    'explore.therapists.services': 'Services:',
    'explore.therapists.more_services': '+{count} more',
    'explore.therapists.filter_specialty': 'Specialty:',
    'explore.therapists.all': 'All',
    'explore.therapists.max_price': 'Max price:',
    'explore.therapists.any_price': 'Any value',
    'explore.therapists.price_100': 'Up to R$ 100',
    'explore.therapists.price_150': 'Up to R$ 150',
    'explore.therapists.price_200': 'Up to R$ 200',
    'explore.therapists.price_300': 'Up to R$ 300',
    'explore.therapists.min_rating': 'Min rating:',
    'explore.therapists.rating_all': 'All',
    'explore.therapists.rating_3': '3+ ⭐',
    'explore.therapists.rating_4': '4+ ⭐',
    'explore.therapists.rating_45': '4.5+ ⭐',
    'explore.therapists.city': 'City:',
    'explore.therapists.city_placeholder': 'e.g., São Paulo',
    'explore.therapists.clear_filters': 'Clear all filters',
    'explore.therapists.saved': 'Therapists you saved to book later',
    // Favorites
    'favorites.title': 'My Favorites',
    'favorites.subtitle': 'Therapists you saved to book later',
    'favorites.empty_title': 'No favorites yet',
    'favorites.empty_desc': 'Browse therapists and save your favorites by clicking the heart icon',
    'favorites.explore_button': 'Explore Therapists',
    'favorites.from_price': 'From R$',
    'favorites.services': 'Services:',
    'favorites.more_services': '+{count} more',
    'favorites.view_profile': 'View Profile & Book',
    // Explore Therapies
    'explore.therapies.title': 'Explore Therapies',
    'explore.therapies.subtitle': 'Discover the best therapeutic practices for your wellness journey',
    'explore.therapies.search_placeholder': 'Search by therapy, indication, modality...',
    'explore.therapies.filter_by_category': 'Filter by Category',
    'explore.therapies.filter_by_indication': 'Filter by Therapeutic Indication',
    'explore.therapies.indications': 'Indications',
    'explore.therapies.contraindications': 'Contraindications',
    'explore.therapies.presencial': 'In-person',
    'explore.therapies.online': 'Online',
    'explore.therapies.presencial_online': 'In-person/Online',
    'explore.therapies.find_therapist': 'Find Therapist',
    'explore.therapies.clear_filters': 'Clear Filters',
    'explore.therapies.no_results': 'No therapies found with these filters.',
    'explore.therapies.more_info': 'More info',
    'explore.therapies.less_info': 'Less info',
  },
  es: {
    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.welcome': 'Bienvenido',
    'dashboard.quick_access': 'Acceso Rápido',
    'dashboard.manage_sessions': 'Gestionar sesiones',
    'dashboard.manage_services': 'Gestionar servicios',
    'dashboard.configure_availability': 'Configurar disponibilidad',
    'dashboard.view_revenue': 'Ver ingresos y pagos',
    'dashboard.find_professionals': 'Encontrar profesionales',
    'dashboard.settings': 'Configuración',
    'dashboard.privacy_title': 'Privacidad y Datos',
    'dashboard.privacy_desc': 'Administra tus datos (exportar, eliminar, consentimientos)',
    // Roles
    'role.therapist': 'Terapeuta',
    'role.client': 'Cliente',
    'role.space': 'Espacio Terapéutico',
    'role.admin': 'Administrador',
    // Auth - Sign In
    'auth.signin.welcome': 'Bienvenido de nuevo',
    'auth.signin.subtitle': 'Inicia sesión para continuar tu viaje',
    'auth.signin.email': 'Correo electrónico',
    'auth.signin.email_placeholder': 'tu@email.com',
    'auth.signin.password': 'Contraseña',
    'auth.signin.password_placeholder': '••••••••',
    'auth.signin.forgot_password': '¿Olvidaste tu contraseña?',
    'auth.signin.signin_button': 'Iniciar sesión',
    'auth.signin.signing_in': 'Iniciando sesión...',
    'auth.signin.verified': '¡Correo verificado con éxito! Ya puedes iniciar sesión.',
    'auth.signin.no_verification': '¿No recibiste el correo de verificación?',
    'auth.signin.resend_button': 'Reenviar correo de verificación',
    'auth.signin.resend_success': '¡Correo reenviado! Revisa tu bandeja de entrada.',
    'auth.signin.resend_error': 'Error al reenviar correo',
    'auth.signin.enter_email': 'Ingresa tu correo primero',
    'auth.signin.or': 'o',
    'auth.signin.no_account': '¿No tienes una cuenta?',
    'auth.signin.signup_link': 'Crear cuenta',
    'auth.signin.secure': 'Seguro y confiable',
    'auth.signin.fast': 'Acceso instantáneo',
    'auth.signin.hero_title': 'Transforma tu viaje de bienestar',
    'auth.signin.hero_subtitle': 'Conéctate con los mejores terapeutas y descubre terapias que cambian vidas.',
    'auth.signin.stat_users': 'Usuarios activos',
    'auth.signin.stat_sessions': 'Sesiones completadas',
    'auth.signin.stat_therapies': 'Terapias disponibles',
    'auth.signin.stat_rating': 'Calificación promedio',
    // Navbar
    'navbar.home': 'Inicio',
    'navbar.bookings': 'Reservas',
    'navbar.services': 'Servicios',
    'navbar.availability': 'Disponibilidad',
    'navbar.revenue': 'Ingresos',
    'navbar.explore': 'Explorar',
    'navbar.therapies': 'Terapias',
    'navbar.favorites': 'Favoritos',
    'navbar.dashboard': 'Panel de Control',
    'navbar.approvals': 'Aprobaciones',
    'navbar.users': 'Usuarios',
    'navbar.bookings_admin': 'Reservas',
    'navbar.news': 'Noticias',
    'navbar.reports': 'Informes',
    'navbar.reviews': 'Reseñas',
    'navbar.payments': 'Pagos',
    'navbar.logout': 'Cerrar Sesión',
    'navbar.profile': 'Mi Perfil',
    'navbar.login': 'Iniciar Sesión',
    'navbar.signup': 'Registrarse',
    'navbar.language': 'Idioma',
    'navbar.documents': 'Documentos',
    'navbar.therapists': 'Terapeutas',
    'navbar.my_bookings': 'Mis Reservas',
    // Dashboard Admin
    'admin.dashboard_title': 'Panel de Administración',
    'admin.total_users': 'Total de Usuarios',
    'admin.therapists': 'Terapeutas',
    'admin.clients': 'Clientes',
    'admin.spaces': 'Espacios',
    'admin.pending_therapists': 'Terapeutas Pendientes',
    'admin.total_bookings': 'Total de Reservas',
    'admin.total_revenue': 'Ingresos Totales',
    // News
    'news.title': 'Noticias',
    'news.new_article': 'Nuevo Artículo',
    'news.edit_article': 'Editar Artículo',
    'news.no_articles': 'No hay artículos publicados',
    'news.create_first': 'Crear primer artículo',
    'news.title_field': 'Título',
    'news.slug_field': 'URL Amigable',
    'news.description_field': 'Descripción (Resumen)',
    'news.content_field': 'Contenido',
    'news.thumbnail_field': 'URL de Imagen de Portada',
    'news.published': 'Publicado',
    'news.draft': 'Borrador',
    'news.featured': 'Destacado',
    'news.mark_featured': 'Marcar como destacado',
    'news.save_article': 'Guardar Artículo',
    'news.saving': 'Guardando...',
    'news.delete_confirm': '¿Estás seguro de que deseas eliminar',
    // Reports
    'reports.title': 'Informes y Análisis',
    'reports.subtitle': 'Resumen de rendimiento y estadísticas de la plataforma',
    'reports.total_users': 'Total de Usuarios',
    'reports.clients': 'Clientes',
    'reports.therapists': 'Terapeutas',
    'reports.bookings': 'Reservas',
    'reports.revenue_30d': 'Ingresos (30d)',
    'reports.bookings_by_day': 'Reservas por Día (últimos 30 días)',
    'reports.users_distribution': 'Distribución de Usuarios por Tipo',
    'reports.top_therapists': 'Top 5 Terapeutas por Reservas',
    'reports.no_bookings': 'No hay reservas registradas',
    // Reviews
    'reviews.title': 'Reseñas y Calificaciones',
    'reviews.subtitle': 'Moderación de reseñas de clientes sobre terapeutas',
    'reviews.total_reviews': 'Total de Reseñas',
    'reviews.avg_rating': 'Calificación Promedio',
    'reviews.distribution': 'Distribución de Votos',
    'reviews.all': 'Todas',
    'reviews.flagged': 'Reportadas',
    'reviews.approved': 'Aprobadas',
    'reviews.no_reviews': 'No hay reseñas disponibles',
    'reviews.flag': 'Marcar como Problemática',
    'reviews.approve': 'Aprobar',
    'reviews.delete': 'Eliminar',
    'reviews.delete_confirm': '¿Estás seguro de que deseas eliminar esta reseña?',
    // Payments
    'payments.title': 'Pagos',
    'payments.subtitle': 'Gestión de transacciones y reembolsos',
    'payments.total_transactions': 'Total en Transacciones',
    'payments.pending': 'Pendientes',
    'payments.refunded': 'Reembolsados',
    'payments.success_rate': 'Tasa de Éxito',
    'payments.completed': 'Completado',
    'payments.failed': 'Fallido',
    'payments.search_placeholder': 'Buscar por terapeuta, cliente o transacción...',
    'payments.all': 'Todos',
    'payments.transaction': 'Transacción',
    'payments.therapist_client': 'Terapeuta / Cliente',
    'payments.amount': 'Monto',
    'payments.status': 'Estado',
    'payments.date': 'Fecha',
    'payments.actions': 'Acciones',
    'payments.refund': 'Reembolsar',
    'payments.processing': 'Procesando...',
    'payments.no_transactions': 'No hay transacciones registradas',
    'payments.refund_confirm': '¿Estás seguro de que deseas reembolsar',
    // Common
    'common.search': 'Buscar...',
    'common.filter': 'Filtrar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Cargando...',
    'common.error': 'Error al cargar datos',
    'common.by': 'Por',
    'common.client': 'Cliente',
    // Checkout y Reservas
    'checkout.title': 'Confirma tu cita',
    'checkout.subtitle': 'Revisa los detalles antes de finalizar',
    'checkout.incomplete': 'Datos de cita incompletos',
    'checkout.back': 'Atrás',
    'checkout.appointment_details': 'Detalles de la Cita',
    'checkout.therapist': 'Terapeuta',
    'checkout.service': 'Servicio',
    'checkout.date_time': 'Fecha y Hora',
    'checkout.payment_method': 'Método de Pago',
    'checkout.credit_card': 'Tarjeta de Crédito',
    'checkout.pix': 'PIX (próximamente)',
    'checkout.cancellation_policy': 'Política de Cancelación',
    'checkout.cancellation_24h': 'Cancelaciones con 24h+ de anticipación: reembolso del 100%',
    'checkout.cancellation_less24h': 'Cancelaciones con hasta 24h: tarifa del 50%',
    'checkout.summary': 'Resumen',
    'checkout.session_value': 'Valor de la sesión',
    'checkout.senda_fee': 'Tarifa Senda (15%)',
    'checkout.total': 'Total',
    'checkout.therapist_receives': 'El terapeuta recibirá R$ {amount} después de completar la sesión',
    'checkout.confirm_payment': 'Confirmar Pago',
    'checkout.processing': 'Procesando...',
    'checkout.error': 'Error al procesar pago',
    'checkout.success_message': '¡Pago procesado exitosamente!',
    // Reserva Exitosa
    'booking.success_title': '¡Todo listo!',
    'booking.success_message': 'Tu sesión ha sido reservada exitosamente. Enviamos un correo de confirmación con todos los detalles.',
    'booking.booking_number': 'Número de reserva',
    'booking.loading_details': 'Cargando detalles...',
    'booking.confirmed_availability': 'Confirmamos disponibilidad',
    'booking.slot_reserved': 'Tu horario está reservado',
    'booking.email_confirmation': 'Confirmación por correo',
    'booking.email_reminder': 'Recibirás recordatorios 24h antes',
    'booking.secure_access': 'Acceso seguro',
    'booking.manage_anytime': 'Administra tu cita en cualquier momento',
    'booking.my_bookings': 'Ir a mis reservas',
    'booking.book_another': 'Reservar otra sesión',
    'booking.cancellation_info': '¿Cambio de opinión? Puedes cancelar con reembolso total hasta 24h antes de la sesión.',
    // Sección de Reservas del Terapeuta
    'therapist.services': 'Servicios',
    'therapist.no_services': 'Este terapeuta no tiene servicios disponibles en este momento.',
    'therapist.schedule_session': 'Programar Sesión',
    'therapist.choose_time': 'Elige Horario',
    'therapist.available_online': 'Disponible en línea',
    'therapist.select_slot': 'Selecciona un horario',
    'therapist.with': 'Con {name}',
    // Página del Terapeuta
    'therapist.title': 'Perfil del Terapeuta',
    'therapist.about': 'Acerca de',
    'therapist.experience': 'Experiencia',
    'therapist.education': 'Educación',
    'therapist.certifications': 'Certificaciones',
    'therapist.specialties': 'Especialidades',
    'therapist.rating': 'Calificación',
    'therapist.reviews': 'Reseñas',
    'therapist.no_reviews': 'Sin reseñas aún',
    'therapist.add_to_favorites': 'Agregar a favoritos',
    'therapist.remove_from_favorites': 'Eliminar de favoritos',
    'therapist.minutes': 'minutos',
    // Servicios del Terapeuta
    'therapist.duration': 'Duración',
    'therapist.from': 'Desde',
    'therapist.schedule': 'Agendar',
    'therapist.created_by': 'Creado por',
    // Senderos y Cursos
    'trails.title': 'Senderos de Aprendizaje',
    'trails.category': 'Categoría',
    'trails.days': 'días',
    'trails.lessons': 'lecciones',
    'trails.start_trail': 'Comenzar Sendero',
    'trails.starting': 'Iniciando...',
    'trails.progress': 'Progreso',
    'trails.of': 'de',
    'trails.completed': '✓ Completado',
    'trails.lessons_title': 'Lecciones',
    'trails.lesson_number': 'Lección',
    'trails.content_type': 'Tipo',
    'trails.text': 'Texto',
    'trails.audio': 'Audio',
    'trails.video': 'Video',
    'trails.mark_complete': 'Marcar como Completado',
    'trails.browser_no_audio': 'Tu navegador no soporta audio',
    'trails.error_enrolling': 'Error al inscribirse',
    'trails.error_general': 'Error al iniciar sendero',
    // Legal y General
    'legal.terms': 'Términos de Servicio',
    'legal.privacy': 'Política de Privacidad',
    'legal.cancellation': 'Política de Cancelación',
    'legal.related_documents': 'Documentos Relacionados',
    'legal.lgpd_compliance': 'Conformidad RGPD',
    // Descubrir/Explorar
    'discover.therapists': 'Descubre Terapeutas Verificados',
    'discover.verified': 'Verificado',
    'discover.therapist_image': 'Imagen del Terapeuta',
    'discover.search_placeholder': 'Busca por ubicación, especialidad, terapeuta...',
    'discover.search_results': 'Terapeutas',
    'discover.new_terms': 'Nuevos Términos de Servicio',
    // Errores de Correo
    'email.error_booking_confirmation': 'Error al enviar confirmación de reserva',
    'email.error_therapist_notification': 'Error al notificar terapeuta',
    'email.error_cancellation': 'Error al enviar cancelación',
    'email.explore_therapists': 'Explorar Terapeutas',
    'email.dashboard_therapist': 'Panel de Terapeutas',
    'email.see_booking_details': 'Ver Detalles de Reserva',
    // Inicio (Landing)
    'home.logo_alt': 'Senda - Tu camino de autocuidado',
    'home.tagline_prefix': 'Tu camino de',
    'home.tagline_highlight': 'autocuidado',
    'home.hero_paragraph': 'El bienestar no es un destino, es un viaje. Te conectamos con profesionales verificados y espacios acogedores para tu camino de cuidado personal.',
    'home.cta_explore_therapists': 'Explorar Terapeutas',
    'home.cta_create_account': 'Crear Cuenta',
    'home.have_account': '¿Ya tienes una cuenta?',
    'home.sign_in': 'Iniciar sesión',
    'home.highlights_title': '✨ Destacados del Mes',
    'home.highlights_subtitle': 'Promociones exclusivas y novedades para tu viaje de bienestar',
    'home.highlight1_title': 'Primera Sesión Gratis',
    'home.highlight1_desc': 'Prueba tu primera sesión gratis con terapeutas seleccionados',
    'home.highlight1_link': 'Ver terapeutas →',
    'home.highlight2_title': 'Paquetes con 20% OFF',
    'home.highlight2_desc': 'Obtén paquetes de 5 o 10 sesiones y ahorra en tu viaje',
    'home.highlight2_link': 'Conocer terapias →',
    'home.highlight3_title': 'Nuevos Terapeutas',
    'home.highlight3_desc': 'Conoce a los profesionales que acaban de unirse a la plataforma',
    'home.highlight3_link': 'Descubrir →',
    'home.how_title': '¿Cómo funciona?',
    'home.how_subtitle': 'Tres pasos simples para iniciar tu viaje de bienestar',
    'home.feature1_title': 'Descubre',
    'home.feature1_desc': 'Explora nuestro catálogo de profesionales verificados. Filtra por especialidad, calificaciones y ubicación para encontrar tu mejor opción.',
    'home.feature2_title': 'Agenda',
    'home.feature2_desc': 'Reserva sesiones con facilidad. Elige fecha y hora que se adapten a tu rutina. Pago seguro y confirmación instantánea.',
    'home.feature3_title': 'Evoluciona',
    'home.feature3_desc': 'Vive tu sesión y sigue tu progreso. Valora tu experiencia y continúa tu camino de autocuidado.',
    'home.trust_title_prefix': 'Profesionales',
    'home.trust_title_highlight': 'verificados',
    'home.trust_paragraph': 'Todos los terapeutas pasan por un riguroso proceso de verificación. Verificamos credenciales, formación académica y experiencia profesional.',
    'home.trust_bullet1': 'Registro profesional validado (licencias, certificaciones)',
    'home.trust_bullet2': 'Reseñas reales de clientes verificados',
    'home.trust_bullet3': 'Política de cancelación humanizada',
    'home.cta_title': '¿Listo para comenzar tu viaje?',
    'home.cta_subtitle': 'Únete a cientos que eligieron el autocuidado como prioridad.',
    'home.cta_button': 'Crear Cuenta Gratis',
    'home.footer_tagline': 'Tu camino de autocuidado comienza aquí.',
    'home.footer_for_clients': 'Para Clientes',
    'home.footer_for_professionals': 'Para Profesionales',
    'home.footer_support': 'Soporte',
    'home.footer_help_center': 'Centro de Ayuda',
    'home.footer_contact': 'Contacto',
    // Explorar Terapeutas
    'explore.therapists.title': 'Rutas de Bienestar',
    'explore.therapists.subtitle': 'Conecta con terapeutas verificados e inicia tu camino de autocuidado. Elige entre cientos de profesionales especializados.',
    'explore.therapists.featured_trails': 'Rutas de bienestar destacadas',
    'explore.therapists.view_all_trails': 'Ver todas',
    'explore.therapists.sort_label': 'Ordenar:',
    'explore.therapists.sort_rating': 'Mejor valorados',
    'explore.therapists.sort_price': 'Menor precio',
    'explore.therapists.sort_recent': 'Más recientes',
    'explore.therapists.sort_distance': 'Distancia',
    'explore.therapists.results_for': 'Resultados para',
    'explore.therapists.verified': 'Terapeutas Verificados',
    'explore.therapists.found': 'profesionales encontrados',
    'explore.therapists.in': 'en',
    'explore.therapists.within': 'en un radio de',
    'explore.therapists.km': 'km',
    'explore.therapists.prev': '← Anterior',
    'explore.therapists.next': 'Siguiente →',
    'explore.therapists.page_of': 'Página {page} de {total}',
    'explore.therapists.no_results_title': 'No se encontraron terapeutas',
    'explore.therapists.no_results_desc': 'Intenta ajustar tus filtros o vuelve pronto',
    'explore.therapists.view_all': 'Ver Todos',
    'explore.therapists.online': 'En línea',
    'explore.therapists.distance': '{value} km de ti',
    'explore.therapists.location_unknown': 'Ubicación no informada',
    'explore.therapists.verified_badge': 'Verificado',
    'explore.therapists.from_price': 'Desde',
    'explore.therapists.view_profile': 'Ver Perfil',
    'explore.therapists.services': 'Servicios:',
    'explore.therapists.more_services': '+{count} más',
    'explore.therapists.filter_specialty': 'Especialidad:',
    'explore.therapists.all': 'Todas',
    'explore.therapists.max_price': 'Precio máximo:',
    'explore.therapists.any_price': 'Cualquier valor',
    'explore.therapists.price_100': 'Hasta R$ 100',
    'explore.therapists.price_150': 'Hasta R$ 150',
    'explore.therapists.price_200': 'Hasta R$ 200',
    'explore.therapists.price_300': 'Hasta R$ 300',
    'explore.therapists.min_rating': 'Calificación mínima:',
    'explore.therapists.rating_all': 'Todas',
    'explore.therapists.rating_3': '3+ ⭐',
    'explore.therapists.rating_4': '4+ ⭐',
    'explore.therapists.rating_45': '4.5+ ⭐',
    'explore.therapists.city': 'Ciudad:',
    'explore.therapists.city_placeholder': 'Ej: São Paulo',
    'explore.therapists.clear_filters': 'Limpiar todos los filtros',
    'explore.therapists.saved': 'Terapeutas que guardaste para agendar después',
    // Favoritos
    'favorites.title': 'Mis Favoritos',
    'favorites.subtitle': 'Terapeutas que guardaste para agendar después',
    'favorites.empty_title': 'Aún no hay favoritos',
    'favorites.empty_desc': 'Explora terapeutas y guarda tus favoritos haciendo clic en el ícono de corazón',
    'favorites.explore_button': 'Explorar Terapeutas',
    'favorites.from_price': 'Desde R$',
    'favorites.services': 'Servicios:',
    'favorites.more_services': '+{count} más',
    'favorites.view_profile': 'Ver Perfil y Agendar',
    // Explorar Terapias
    'explore.therapies.title': 'Explorar Terapias',
    'explore.therapies.subtitle': 'Descubra las mejores prácticas terapéuticas para su viaje de bienestar',
    'explore.therapies.search_placeholder': 'Buscar por terapia, indicación, modalidad...',
    'explore.therapies.filter_by_category': 'Filtrar por Categoría',
    'explore.therapies.filter_by_indication': 'Filtrar por Indicación Terapéutica',
    'explore.therapies.indications': 'Indicaciones',
    'explore.therapies.contraindications': 'Contraindicaciones',
    'explore.therapies.presencial': 'Presencial',
    'explore.therapies.online': 'En línea',
    'explore.therapies.presencial_online': 'Presencial/En línea',
    'explore.therapies.find_therapist': 'Encontrar Terapeuta',
    'explore.therapies.clear_filters': 'Limpiar Filtros',
    'explore.therapies.no_results': 'No se encontraron terapias con estos filtros.',
    'explore.therapies.more_info': 'Más info',
    'explore.therapies.less_info': 'Menos info',
  },
  zh: {
    // Dashboard
    'dashboard.title': '仪表盘',
    'dashboard.welcome': '欢迎',
    'dashboard.quick_access': '快速访问',
    'dashboard.manage_sessions': '管理会话',
    'dashboard.manage_services': '管理服务',
    'dashboard.configure_availability': '设置可用时间',
    'dashboard.view_revenue': '查看收入与结算',
    'dashboard.find_professionals': '寻找专业人士',
    'dashboard.settings': '设置',
    'dashboard.privacy_title': '隐私与数据',
    'dashboard.privacy_desc': '按照数据保护法管理您的数据（导出、删除、同意）',
    // Roles
    'role.therapist': '治疗师',
    'role.client': '客户',
    'role.space': '治疗空间',
    'role.admin': '管理员',
    // Auth - Sign In
    'auth.signin.welcome': '欢迎回来',
    'auth.signin.subtitle': '登录您的账户以继续您的旅程',
    'auth.signin.email': '电子邮件',
    'auth.signin.email_placeholder': 'your@email.com',
    'auth.signin.password': '密码',
    'auth.signin.password_placeholder': '••••••••',
    'auth.signin.forgot_password': '忘记密码？',
    'auth.signin.signin_button': '登录',
    'auth.signin.signing_in': '登录中...',
    'auth.signin.verified': '邮箱验证成功！您现在可以登录了。',
    'auth.signin.no_verification': '没有收到验证邮件？',
    'auth.signin.resend_button': '重新发送验证邮件',
    'auth.signin.resend_success': '邮件已重新发送！请查看您的收件箱。',
    'auth.signin.resend_error': '重新发送邮件时出错',
    'auth.signin.enter_email': '请先输入您的电子邮件',
    'auth.signin.or': '或',
    'auth.signin.no_account': '还没有账户？',
    'auth.signin.signup_link': '注册',
    'auth.signin.secure': '安全可信',
    'auth.signin.fast': '即时访问',
    'auth.signin.hero_title': '改变您的健康之旅',
    'auth.signin.hero_subtitle': '与最好的治疗师联系，发现改变生活的疗法。',
    'auth.signin.stat_users': '活跃用户',
    'auth.signin.stat_sessions': '完成的会话',
    'auth.signin.stat_therapies': '可用疗法',
    'auth.signin.stat_rating': '平均评分',
    // Navbar
    'navbar.home': '首页',
    'navbar.bookings': '预订',
    'navbar.services': '服务',
    'navbar.availability': '可用性',
    'navbar.revenue': '收入',
    'navbar.explore': '探索',
    'navbar.therapies': '疗法',
    'navbar.favorites': '收藏',
    'navbar.dashboard': '仪表板',
    'navbar.approvals': '批准',
    'navbar.users': '用户',
    'navbar.bookings_admin': '预订',
    'navbar.news': '新闻',
    'navbar.reports': '报告',
    'navbar.reviews': '评论',
    'navbar.payments': '支付',
    'navbar.logout': '退出登录',
    'navbar.profile': '我的资料',
    'navbar.login': '登录',
    'navbar.signup': '注册',
    'navbar.language': '语言',
    'navbar.documents': '文件',
    'navbar.therapists': '治疗师',
    'navbar.my_bookings': '我的预订',
    // Dashboard Admin
    'admin.dashboard_title': '管理仪表板',
    'admin.total_users': '用户总数',
    'admin.therapists': '治疗师',
    'admin.clients': '客户端',
    'admin.spaces': '空间',
    'admin.pending_therapists': '待审批治疗师',
    'admin.total_bookings': '总预订数',
    'admin.total_revenue': '总收入',
    // News
    'news.title': '新闻',
    'news.new_article': '新文章',
    'news.edit_article': '编辑文章',
    'news.no_articles': '没有已发布的文章',
    'news.create_first': '创建第一篇文章',
    'news.title_field': '标题',
    'news.slug_field': 'URL别名',
    'news.description_field': '描述（摘要）',
    'news.content_field': '内容',
    'news.thumbnail_field': '封面图片网址',
    'news.published': '已发布',
    'news.draft': '草稿',
    'news.featured': '精选',
    'news.mark_featured': '标记为精选',
    'news.save_article': '保存文章',
    'news.saving': '保存中...',
    'news.delete_confirm': '您确定要删除',
    // Reports
    'reports.title': '报告与分析',
    'reports.subtitle': '平台性能概览和统计数据',
    'reports.total_users': '用户总数',
    'reports.clients': '客户',
    'reports.therapists': '治疗师',
    'reports.bookings': '预订',
    'reports.revenue_30d': '收入（30天）',
    'reports.bookings_by_day': '每日预订（最近30天）',
    'reports.users_distribution': '按类型的用户分布',
    'reports.top_therapists': '预订量前5名治疗师',
    'reports.no_bookings': '没有记录的预订',
    // Reviews
    'reviews.title': '评论与评分',
    'reviews.subtitle': '客户对治疗师的评论审核',
    'reviews.total_reviews': '总评论数',
    'reviews.avg_rating': '平均评分',
    'reviews.distribution': '投票分布',
    'reviews.all': '全部',
    'reviews.flagged': '已举报',
    'reviews.approved': '已批准',
    'reviews.no_reviews': '没有可用的评论',
    'reviews.flag': '标记为问题',
    'reviews.approve': '批准',
    'reviews.delete': '删除',
    'reviews.delete_confirm': '您确定要删除此评论吗？',
    // Payments
    'payments.title': '支付',
    'payments.subtitle': '交易和退款管理',
    'payments.total_transactions': '交易总额',
    'payments.pending': '待处理',
    'payments.refunded': '已退款',
    'payments.success_rate': '成功率',
    'payments.completed': '已完成',
    'payments.failed': '失败',
    'payments.search_placeholder': '按治疗师、客户或交易搜索...',
    'payments.all': '全部',
    'payments.transaction': '交易',
    'payments.therapist_client': '治疗师/客户',
    'payments.amount': '金额',
    'payments.status': '状态',
    'payments.date': '日期',
    'payments.actions': '操作',
    'payments.refund': '退款',
    'payments.processing': '处理中...',
    'payments.no_transactions': '没有记录的交易',
    'payments.refund_confirm': '您确定要退款',
    // Common
    'common.search': '搜索...',
    'common.filter': '筛选',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.loading': '加载中...',
    'common.error': '加载数据出错',
    'common.by': '由',
    'common.client': '客户',
    // 结账和预订
    'checkout.title': '确认您的预约',
    'checkout.subtitle': '在完成前检查详细信息',
    'checkout.incomplete': '预约数据不完整',
    'checkout.back': '返回',
    'checkout.appointment_details': '预约详情',
    'checkout.therapist': '治疗师',
    'checkout.service': '服务',
    'checkout.date_time': '日期和时间',
    'checkout.payment_method': '付款方式',
    'checkout.credit_card': '信用卡',
    'checkout.pix': 'PIX（即将推出）',
    'checkout.cancellation_policy': '取消政策',
    'checkout.cancellation_24h': '提前24小时以上取消：100%退款',
    'checkout.cancellation_less24h': '提前不足24小时取消：50%费用',
    'checkout.summary': '摘要',
    'checkout.session_value': '会议价值',
    'checkout.senda_fee': 'Senda费用（15%）',
    'checkout.total': '总计',
    'checkout.therapist_receives': '治疗师在会议完成后将收到R$ {amount}',
    'checkout.confirm_payment': '确认付款',
    'checkout.processing': '处理中...',
    'checkout.error': '支付处理出错',
    'checkout.success_message': '支付处理成功！',
    // 预订成功
    'booking.success_title': '一切就绪！',
    'booking.success_message': '您的会议已成功预订。我们发送了包含所有详细信息的确认电子邮件。',
    'booking.booking_number': '预订编号',
    'booking.loading_details': '加载详情...',
    'booking.confirmed_availability': '我们确认了可用性',
    'booking.slot_reserved': '您的时间段已保留',
    'booking.email_confirmation': '电子邮件确认',
    'booking.email_reminder': '您将收到24小时前的提醒',
    'booking.secure_access': '安全访问',
    'booking.manage_anytime': '随时管理您的预约',
    'booking.my_bookings': '转到我的预订',
    'booking.book_another': '预订另一场会议',
    'booking.cancellation_info': '改变主意了？您可以在会议前24小时内取消并获得全额退款。',
    // 治疗师预订部分
    'therapist.services': '服务',
    'therapist.no_services': '此治疗师目前没有可用的服务。',
    'therapist.schedule_session': '安排会议',
    'therapist.choose_time': '选择时间',
    'therapist.available_online': '在线可用',
    'therapist.select_slot': '选择时间段',
    'therapist.with': '与 {name}',
    // 治疗师页面
    'therapist.title': '治疗师简介',
    'therapist.about': '关于',
    'therapist.experience': '经验',
    'therapist.education': '教育',
    'therapist.certifications': '证书',
    'therapist.specialties': '专业领域',
    'therapist.rating': '评分',
    'therapist.reviews': '评论',
    'therapist.no_reviews': '还没有评论',
    'therapist.add_to_favorites': '添加到收藏',
    'therapist.remove_from_favorites': '从收藏中移除',
    'therapist.minutes': '分钟',
    // 治疗师服务
    'therapist.duration': '持续时间',
    'therapist.from': '从',
    'therapist.schedule': '日程',
    'therapist.created_by': '创建者',
    // 学习路径和课程
    'trails.title': '学习路径',
    'trails.category': '类别',
    'trails.days': '天',
    'trails.lessons': '课程',
    'trails.start_trail': '开始路径',
    'trails.starting': '启动中...',
    'trails.progress': '进度',
    'trails.of': '的',
    'trails.completed': '✓ 已完成',
    'trails.lessons_title': '课程',
    'trails.lesson_number': '课程',
    'trails.content_type': '类型',
    'trails.text': '文本',
    'trails.audio': '音频',
    'trails.video': '视频',
    'trails.mark_complete': '标记为完成',
    'trails.browser_no_audio': '您的浏览器不支持音频',
    'trails.error_enrolling': '注册失败',
    'trails.error_general': '启动路径时出错',
    // 法律和通用
    'legal.terms': '服务条款',
    'legal.privacy': '隐私政策',
    'legal.cancellation': '取消政策',
    'legal.related_documents': '相关文件',
    'legal.lgpd_compliance': '数据保护合规',
    // 发现/探索
    'discover.therapists': '发现已验证的治疗师',
    'discover.verified': '已验证',
    'discover.therapist_image': '治疗师图片',
    'discover.search_placeholder': '按位置、专业或治疗师搜索...',
    'discover.search_results': '治疗师',
    'discover.new_terms': '新服务条款',
    // 电子邮件错误
    'email.error_booking_confirmation': '发送预订确认时出错',
    'email.error_therapist_notification': '通知治疗师时出错',
    'email.error_cancellation': '发送取消时出错',
    'email.explore_therapists': '探索治疗师',
    'email.dashboard_therapist': '治疗师仪表板',
    'email.see_booking_details': '查看预订详情',
    // 首页（登陆页）
    'home.logo_alt': 'Senda - 您的自我关怀之路',
    'home.tagline_prefix': '您的',
    'home.tagline_highlight': '自我关怀之路',
    'home.hero_paragraph': '健康不是终点，而是一段旅程。我们将您与经过验证的专业人士和温馨空间相连，助力您的自我关怀之路。',
    'home.cta_explore_therapists': '探索治疗师',
    'home.cta_create_account': '创建账户',
    'home.have_account': '已有账户？',
    'home.sign_in': '登录',
    'home.highlights_title': '✨ 本月亮点',
    'home.highlights_subtitle': '为您的健康之旅提供独家优惠与最新资讯',
    'home.highlight1_title': '首次会话免费',
    'home.highlight1_desc': '与精选治疗师免费体验您的第一场会话',
    'home.highlight1_link': '查看治疗师 →',
    'home.highlight2_title': '套餐立减20%',
    'home.highlight2_desc': '购买5或10次会话套餐，为您的旅程省钱',
    'home.highlight2_link': '了解疗法 →',
    'home.highlight3_title': '新入驻治疗师',
    'home.highlight3_desc': '认识刚加入平台的专业人士',
    'home.highlight3_link': '去发现 →',
    'home.how_title': '如何运作？',
    'home.how_subtitle': '三个简单步骤开启健康之旅',
    'home.feature1_title': '探索',
    'home.feature1_desc': '浏览我们经过验证的专业人士目录。按专长、评分和位置筛选，找到最适合您的选项。',
    'home.feature2_title': '预约',
    'home.feature2_desc': '轻松预约会话。选择适合您日程的日期和时间。安全支付并即时确认。',
    'home.feature3_title': '成长',
    'home.feature3_desc': '参与会话并跟踪进展。评价您的体验，持续自我关怀之路。',
    'home.trust_title_prefix': '专业',
    'home.trust_title_highlight': '认证',
    'home.trust_paragraph': '所有治疗师都经过严格的审核流程。我们核验资质、教育背景与专业经验。',
    'home.trust_bullet1': '专业资质验证（执照、认证）',
    'home.trust_bullet2': '来自已验证客户的真实评价',
    'home.trust_bullet3': '人性化的取消政策',
    'home.cta_title': '准备好开始您的旅程了吗？',
    'home.cta_subtitle': '加入将自我关怀作为优先事项的数百人行列。',
    'home.cta_button': '创建免费账户',
    'home.footer_tagline': '您的自我关怀之路从这里开始。',
    'home.footer_for_clients': '面向客户',
    'home.footer_for_professionals': '面向专业人士',
    'home.footer_support': '支持',
    'home.footer_help_center': '帮助中心',
    'home.footer_contact': '联系',
    // 探索治疗师
    'explore.therapists.title': '健康路线',
    'explore.therapists.subtitle': '连接经过验证的治疗师，开始你的自我关怀之旅。选择数百位专业人士。',
    'explore.therapists.featured_trails': '精选健康路线',
    'explore.therapists.view_all_trails': '查看全部',
    'explore.therapists.sort_label': '排序：',
    'explore.therapists.sort_rating': '评分最高',
    'explore.therapists.sort_price': '价格最低',
    'explore.therapists.sort_recent': '最新',
    'explore.therapists.sort_distance': '距离',
    'explore.therapists.results_for': '结果：',
    'explore.therapists.verified': '已验证治疗师',
    'explore.therapists.found': '位专业人士',
    'explore.therapists.in': '在',
    'explore.therapists.within': '范围',
    'explore.therapists.km': '公里',
    'explore.therapists.prev': '← 上一页',
    'explore.therapists.next': '下一页 →',
    'explore.therapists.page_of': '第 {page} 页 / 共 {total} 页',
    'explore.therapists.no_results_title': '未找到治疗师',
    'explore.therapists.no_results_desc': '尝试调整筛选条件或稍后再来',
    'explore.therapists.view_all': '查看全部',
    'explore.therapists.online': '在线',
    'explore.therapists.distance': '距你 {value} 公里',
    'explore.therapists.location_unknown': '位置未提供',
    'explore.therapists.verified_badge': '已验证',
    'explore.therapists.from_price': '起价',
    'explore.therapists.view_profile': '查看资料',
    'explore.therapists.services': '服务：',
    'explore.therapists.more_services': '+{count} 项更多',
    'explore.therapists.filter_specialty': '专长：',
    'explore.therapists.all': '全部',
    'explore.therapists.max_price': '最高价格：',
    'explore.therapists.any_price': '不限价格',
    'explore.therapists.price_100': '不高于 R$ 100',
    'explore.therapists.price_150': '不高于 R$ 150',
    'explore.therapists.price_200': '不高于 R$ 200',
    'explore.therapists.price_300': '不高于 R$ 300',
    'explore.therapists.min_rating': '最低评分：',
    'explore.therapists.rating_all': '全部',
    'explore.therapists.rating_3': '3+ ⭐',
    'explore.therapists.rating_4': '4+ ⭐',
    'explore.therapists.rating_45': '4.5+ ⭐',
    'explore.therapists.city': '城市：',
    'explore.therapists.city_placeholder': '例如：São Paulo',
    'explore.therapists.clear_filters': '清除全部筛选',
    'explore.therapists.saved': '你已保存的治疗师，方便稍后预约',
    // 收藏
    'favorites.title': '我的收藏',
    'favorites.subtitle': '你保存的治疗师，方便稍后预约',
    'favorites.empty_title': '还没有收藏',
    'favorites.empty_desc': '探索治疗师并点击心形图标保存你的收藏',
    'favorites.explore_button': '探索治疗师',
    'favorites.from_price': '起价 R$',
    'favorites.services': '服务：',
    'favorites.more_services': '+{count} 项更多',
    'favorites.view_profile': '查看资料并预约',
    // 探索疗法
    'explore.therapies.title': '探索疗法',
    'explore.therapies.subtitle': '为您的健康之旅发现最佳治疗实践',
    'explore.therapies.search_placeholder': '按疗法、适应症或方式搜索...',
    'explore.therapies.filter_by_category': '按类别筛选',
    'explore.therapies.filter_by_indication': '按治疗指示筛选',
    'explore.therapies.indications': '指示',
    'explore.therapies.contraindications': '禁忌',
    'explore.therapies.presencial': '当面',
    'explore.therapies.online': '在线',
    'explore.therapies.presencial_online': '当面/在线',
    'explore.therapies.find_therapist': '查找治疗师',
    'explore.therapies.clear_filters': '清除过滤器',
    'explore.therapies.no_results': '未找到符合这些过滤器的疗法。',
    'explore.therapies.more_info': '更多信息',
    'explore.therapies.less_info': '更少信息',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pt')
  const [mounted, setMounted] = useState(false)

  // Carregar idioma salvo do localStorage apenas no client
  useEffect(() => {
    setMounted(true)
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language') as Language
      if (saved && Object.keys(translations).includes(saved)) {
        setLanguageState(saved)
      }
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang)
    }
  }

  const t = (key: string, params?: Record<string, string | number>): string => {
    // Busca direta primeiro (chaves com pontos como 'auth.signin.welcome')
    let translation = (translations[language] as Record<string, any>)[key]
    if (translation) {
      // Substituir variáveis {var} se params fornecido
      if (params) {
        Object.keys(params).forEach(paramKey => {
          translation = translation.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(params[paramKey]))
        })
      }
      return translation
    }
    
    // Fallback para busca aninhada (se necessário no futuro)
    const keys = key.split('.')
    let current: any = translations[language]
    
    for (const k of keys) {
      if (current && typeof current === 'object' && k in current) {
        current = current[k]
      } else {
        return key // Retorna a chave se não encontrar
      }
    }
    
    if (typeof current === 'string') {
      // Substituir variáveis {var} se params fornecido
      if (params) {
        Object.keys(params).forEach(paramKey => {
          current = current.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(params[paramKey]))
        })
      }
      return current
    }
    
    return key
  }

  // Evitar flash de conteúdo não traduzido
  if (!mounted) {
    return null
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    return {
      language: 'pt' as Language,
      setLanguage: () => {},
      t: (key: string, params?: Record<string, string | number>) => key,
    }
  }
  return context
}
